### ISSUE TITLE
turn-on-orglink-mode-if-desired: Symbol’s value as variable is void: org-link-descriptive

### ISSUE THREAD

**Issue by 717g301github** [tarsius/orglink#8] opened 2019-10-06 05:48 UTC
When attempting to M-x global-orglink-mode this is error that I get:

turn-on-orglink-mode-if-desired: Symbol’s value as variable is void: org-link-descriptive

Using Emacs from git:

GNU Emacs 27.0.50 (build 5, x86_64-pc-linux-gnu, X toolkit, Xaw3d scroll bars) of 2019-09-07

**Comment by tarsius** [comment] 2019-10-06 09:19
Duplicate of #6.

**Closed by tarsius** 2019-10-06 09:19 UTC
Labels: duplicate, support
